# Generated by Django 2.2.6 on 2019-11-12 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('puntos', '0003_auto_20191027_1802'),
        ('users', '0002_googleuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=15)),
                ('imagen', models.ImageField(blank=True, default=None, null=True, upload_to='planes')),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Perfil')),
                ('likes', models.ManyToManyField(blank=True, default=None, to='planes.Valoracion')),
                ('puntos', models.ManyToManyField(related_name='punto', to='puntos.Punto')),
            ],
        ),
    ]
