# Generated by Django 2.2.6 on 2019-10-20 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('puntos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=15)),
                ('likes', models.IntegerField()),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Perfil')),
                ('puntos', models.ManyToManyField(to='puntos.Punto')),
            ],
        ),
    ]
