# Generated by Django 2.2.6 on 2019-10-20 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planes',
            name='likes',
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Perfil')),
            ],
        ),
        migrations.AddField(
            model_name='planes',
            name='likes',
            field=models.ManyToManyField(to='planes.Valoracion'),
        ),
    ]
