# Generated by Django 2.2.6 on 2019-10-27 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planes',
            name='likes',
        ),
    ]
