# Generated by Django 2.2.6 on 2019-11-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planes',
            name='imagen',
            field=models.ImageField(upload_to='planes'),
        ),
    ]
