# Generated by Django 2.2.6 on 2019-10-27 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('puntos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='punto',
            name='creador',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Perfil', verbose_name='creador'),
        ),
        migrations.AlterField(
            model_name='punto',
            name='nombre',
            field=models.CharField(max_length=25),
        ),
    ]
