# Generated by Django 2.2.6 on 2019-10-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('puntos', '0002_auto_20191027_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punto',
            name='creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Perfil', verbose_name='creador'),
        ),
    ]
